MODEL:
  META_ARCHITECTURE: "AnchorFreeNetwork"
  BACKBONE:
    FREEZE_AT: 2
DATALOADER:
  NUM_WORKERS: 4
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (60000, 80000) #(210000, 250000)
  MAX_ITER: 90000       #270000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
TEST:
  EVAL_PERIOD: 5000


