_BASE_: "base.yaml"
MODEL:
  BACKBONE:
    NAME: "build_resnet_backbone"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
    OUT_FEATURES: ["res4"]
  RPN:
    IN_FEATURES: ["res4"]
  ROI_HEADS:
    IN_FEATURES: ["res4"]
OUTPUT_DIR: "./output/r50"
