_BASE_: "base.yaml"
MODEL:
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  ANCHOR_FREE_HEADS:
    NAME: "RepHead"
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
OUTPUT_DIR: "./output/reppoints_fpn"